### PR TITLE
(#166) Bunch of fixes

### LINKED ISSUE #166: Make all links in the app open in a new tab
This is pretty self-explanatory, `target="_blank"` should do the trick

### LINKED ISSUE #167: Adjust testimonials to designs
### Description
The testimonials are quite different compared to designs, please fix the component visually (the main issue is the shadow placement)

### Screenshots

**Current style:**

**Desired style:**

### PR DESCRIPTION
**Pull request by dominikslawkowski**

### CODE REVIEW

File: src/components/Button/Button.tsx [hunk 1]
```diff
@@ -17,3 +20,10 @@ export const Button = (props: ButtonProps) => {
 
   return <MuiButton className={classes.button} {...props} />;
 };
+
+const defaultButtonProps: ButtonProps = {
+  rel: 'noopener noreferrer',
+  target: '_blank',
```
Comment (KonradSzwarc) [inline src/components/Button/Button.tsx]: Wouldn't it render all of our buttons as links?
Also, I know it will be more robust, but in my opinion, it would be better if we pass those props explicitly when using the Button component

File: src/components/Button/Button.tsx [hunk 2]
```diff
@@ -1,7 +1,10 @@
 import React from 'react';
 import { Button as MuiButton, ButtonProps as MuiButtonProps, makeStyles } from '@material-ui/core';
 
-export type ButtonProps = MuiButtonProps;
+export type ButtonProps = MuiButtonProps & {
```
Comment (KonradSzwarc) [inline src/components/Button/Button.tsx]: Aren't those props available for material buttons by default when we render them as anchors?

**Review by KonradSzwarc — CHANGES_REQUESTED** [review]

File: src/components/Button/Button.tsx (hunk 2 above)
Comment (mecies) [reply src/components/Button/Button.tsx]: @KonradSzwarc  if I remember correctly, this was because we do not have `strictNullChecks` set to `true` in `tsconfig`

See:
https://github.com/mui-org/material-ui/issues/22699

File: src/components/Button/Button.tsx (hunk 1 above)
Comment (mecies) [reply src/components/Button/Button.tsx]: I suppose it would, please double-check @dominikslawkowski

**Review by mecies — COMMENTED** [review]
Please address two comments from @KonradSzwarc , other than that, looks good to me 😄

File: src/components/Button/Button.tsx (hunk 2 above)
Comment (KonradSzwarc) [reply src/components/Button/Button.tsx]: Ok, adding `strictNullChecks` to our tsconfig looks like a great solution

Comment (mecies) [reply src/components/Button/Button.tsx]: I agree 😄

**Review by KonradSzwarc — APPROVED** [review]

**Review by mecies — APPROVED** [review]
Out of curiosity, strict null checks didn't fix the issue?
