### PR TITLE
Verify box shadows application-wide

### LINKED ISSUE #130: Verify box shadows application-wide
I've noticed that `box shadows` in our app are plain strings, if they are repeated, they should come from the theme.
Please verify with designs all box shadows and if they are repeated add them to the theme, also if some are incorrect please replace them with correct ones from the designs

[LINK TO DESIGNS](https://www.figma.com/file/bM9b4fMCze8dgwzRzvMaNp/CodersCard-Mockups)

HINT: search for `boxShadow` in your IDE in the root directory

### PR DESCRIPTION
**Pull request by celinawierzbicka**
Closes #130

### CODE REVIEW

File: src/utils/theme.tsx [hunk 1]
```diff
@@ -97,6 +97,33 @@ const themeOptions: ThemeOptions = {
...
+    'none',
+    'none',
+    'none',
+    'none',
+    'none',
+    'none',
+    'none',
+    'none',
+    'none',
+    'none',
```
Comment (mecies) [inline src/utils/theme.tsx]: You can probably change it to 1 line and leave a comment that material UI requires exactly 25 box shadows
```javascript
...[...Array(18)].map((_) => `none`)
```

**Review by mecies — CHANGES_REQUESTED** [review]
Nice job 💪 , only one comment to decrease the theme file size 😄

File: src/utils/theme.tsx (hunk 1 above)
Comment (celinawierzbicka) [reply src/utils/theme.tsx]: for some reason typescript doesn't like that approach with spread operator :thinking:

Comment (mecies) [reply src/utils/theme.tsx]: I think that in this case, you can tell typescript explicitly that it will be of type Shadows like so:
```typescript
import { Shadows } from '@material-ui/core/styles/shadows';
...
shadows: [
    'none',
    '0px 0px 0px 0px rgba(0,0,0,0.2)',
    '0 6px 16px 0 rgba(0, 0, 0, 0.1)',
    '0px 10px 40px -10px rgba(0,0,0,0.2)',
    '0 8px 20px 0 rgba(68, 86, 108, 0.1)',
    '0 40px 50px 0 rgba(103, 118, 128, 0.1)',
    '0 2px 4px 0 rgba(47, 84, 235, 0.15), 0 8px 16px 0 rgba(47, 84, 235, 0.15)',
    ...[...Array(18)].map((_) => `none`),
  ] as Shadows,
...
```

**Review by mecies — APPROVED** [review]
Nice job ✅ 
Ready to merge 👍

**Review by KlaraGajaszek — APPROVED** [review]
